SELECT 1;
-- INSERT INTO users (id, email, firstname, password)
-- VALUES (1, 'uinan@miu.edu', 'umur', '$2a$12$IKEQb00u5QpZMx4v5zMweu.3wrq0pS7XLCHO4yHZ.BW/yvWu1feo2'); --123
-- INSERT INTO users (id, email, firstname, password)
-- VALUES (2, 'john@miu.edu', 'john', '$2a$12$IKEQb00u5QpZMx4v5zMweu.3wrq0pS7XLCHO4yHZ.BW/yvWu1feo2'); --123
-- INSERT INTO users (id, email, firstname, password)
-- VALUES (3, 'dean@miu.edu', 'Dean', '$2a$12$IKEQb00u5QpZMx4v5zMweu.3wrq0pS7XLCHO4yHZ.BW/yvWu1feo2'); --123
--
-- INSERT INTO role (id, name)
-- VALUES (1, 'ADMIN');
-- INSERT INTO role (id, name)
-- VALUES (2, 'CLIENT');
--
--
-- INSERT INTO users_roles (user_id, roles_id)
-- VALUES (1, 1);
-- INSERT INTO users_roles (user_id, roles_id)
-- VALUES (2, 1);
-- INSERT INTO users_roles (user_id, roles_id)
-- VALUES (3, 2);
-- --
-- -- INSERT INTO product (id, name, price, id_user)
-- -- VALUES (1, 'iPhone', 1200, 1);
-- -- INSERT INTO product (id, name, price, id_user)
-- -- VALUES (2, 'iPad', 900, 1);
-- -- INSERT INTO product (id, name, price, id_user)
-- -- VALUES (3, 'Pen', 5, 1);